require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
require 'rails_helper'

RSpec.describe EntriesController, type: :controller do
  before(:each) do
    @incoming1 = create(:incoming)
    @incoming2 = create(:incoming)
  end

  describe "GET #index" do
    it "returns a success response" do
      get :index
      expect(response).to be_successful
    end

    it "returns all incomings as JSON" do
      get :index
      parsed_body = JSON.parse(response.body)

      expect(parsed_body.length).to eq 2
      expect(parsed_body.first["id"]).to eq @incoming1.id
      expect(parsed_body.second["id"]).to eq @incoming2.id
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      get :show, params: { id: @incoming1.id }
      expect(response).to be_successful
    end

    it "returns the correct incoming as JSON" do
      get :show, params: { id: @incoming1.id }
      parsed_body = JSON.parse(response.body)

      expect(parsed_body["id"]).to eq @incoming1.id
    end
  end

  after(:each) do
    Incoming.destroy_all
  end
end